<a href="https://colab.research.google.com/github/mfarooq33/Advance-DL-with-Keras/blob/master/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.7037,  1.6204, -1.5314], requires_grad=True)


In [ ]:
y = x+2
print(y)

tensor([2.7037, 3.6204, 0.4686], grad_fn=<AddBackward0>)


In [ ]:
z= y*y*2
z=z.mean()
print(z)

tensor(13.7579, grad_fn=<MeanBackward0>)


In [ ]:
v =torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward()
print(x.grad)

tensor([3.6049, 4.8272, 0.6248])


In [ ]:
# How apply the Grident
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad(): 

In [ ]:
x.requires_grad_(False)
print(x)

tensor([ 0.7037,  1.6204, -1.5314])


In [ ]:
y = x.detach()
print(y)

tensor([ 0.7037,  1.6204, -1.5314])


In [ ]:
with torch.no_grad():
  y = x+2
  print(y)

tensor([2.7037, 3.6204, 0.4686])


In [ ]:
import torch
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [ ]:
weights.grad.zero_()

tensor([0., 0., 0., 0.])

In [ ]:
import torch
weights = torch.ones(4, requires_grad=True)
#optim = RAdam([theta], 1, betas=(0.9, 0.95), eps=1e-5, weight_decay=0)
#weights.type(torch.DoubleTensor)
optimizer = torch.optim.SGD(weights, lr = 0.01)
optimizer.step()
optimizer.zero_grad()

TypeError: ignored